services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $migrationDirectory: "%doctrine_migrations.dir_name%"

    StfalconStudio\DoctrineRedisCacheBundle\Service\Migration\MigrationVersionService:
        class: StfalconStudio\DoctrineRedisCacheBundle\Service\Migration\MigrationVersionService

    Doctrine\Migrations\Finder\MigrationFinder:
        class: Doctrine\Migrations\Finder\RecursiveRegexFinder
